// app/lib/config.ts
// -----------------------------------------------------------------------------
// Single source of truth for store-specific values (see AI_CONTEXT.md §2/§3).
// Rule: the dev→prod cutover must only ever touch this file and .env.
// Anything read from `env` is set via `npx shopify hydrogen env pull` or the
// Hydrogen channel's environment-variable settings (per environment).
// -----------------------------------------------------------------------------

export const config = {
  /** Product + collection handles — MUST be identical in dev and prod admin. */
  productHandle: 'le-filtre-a-eau-par-gravite-phoenix-test', // TODO: change to 'the-phoenix-gravity-wasserfilter' once created in Shopify admin
  collectionAllHandle: 'all-products',

  /** Free-shipping threshold used by the cart drawer progress bar. */
  freeShippingThresholdEUR: 99,

  /** Locale — the storefront client must also be created with DE/DE i18n. */
  currency: 'EUR' as const,
  locale: 'de-DE' as const,

  /** Contact details rendered in the footer. TODO: finalize before launch. */
  contactEmail: 'support@example.de', // TODO
  contactPhone: '+49 000 0000000', // TODO

  /** Review provider — Judge.me (see app/lib/reviews.server.ts). */
  reviewProvider: 'judgeme' as const,

  /** Impact calculator assumptions (documented in the section footnote). */
  impact: {
    litresPerPersonPerDay: 2,
    bottlesPerPersonPerYear: 180,
    co2KgPerBottle: 0.11,
    savingsEurPerBottle: 0.6,
    filterCapacityLitres: 20_000, // per cartridge pair
    filterLifetimeMonths: 12,
    minPeople: 1,
    maxPeople: 8,
    defaultPeople: 2,
  },
} as const;

export type StoreConfig = typeof config;

/**
 * Helper for values that come from environment variables (server-side).
 * Call from loaders: `getEnvConfig(context.env)`.
 */
export function getEnvConfig(env: Env) {
  return {
    gtmId: env.PUBLIC_GTM_ID ?? '',
    canonicalDomain: env.PUBLIC_CANONICAL_DOMAIN ?? '',
    heroVideoUrl: env.PUBLIC_HERO_VIDEO_URL ?? '',
    heroPosterUrl: env.PUBLIC_HERO_POSTER_URL ?? '',
    judgeme: {
      // Private token — server-only. Never expose to the client bundle.
      apiToken: env.JUDGEME_PRIVATE_TOKEN ?? '',
      // The myshopify.com domain of the CURRENTLY LINKED store, e.g.
      // "phoenix-de-dev.myshopify.com" — differs between dev and prod.
      shopDomain: env.JUDGEME_SHOP_DOMAIN ?? '',
    },
  };
}

/**
 * Format a number as EUR currency.
 * Usage: formatEUR(99) → "99,00 €"
 */
export function formatEUR(amount: number): string {
  return new Intl.NumberFormat('de-DE', {
    style: 'currency',
    currency: 'EUR',
  }).format(amount);
}

/**
 * Extend the ambient Env interface generated by Hydrogen with our custom vars.
 * (Alternatively place this in env.d.ts.)
 */
declare global {
  interface Env {
    PUBLIC_GTM_ID?: string;
    PUBLIC_CANONICAL_DOMAIN?: string;
    PUBLIC_HERO_VIDEO_URL?: string;
    PUBLIC_HERO_POSTER_URL?: string;
    JUDGEME_PRIVATE_TOKEN?: string;
    JUDGEME_SHOP_DOMAIN?: string;
  }
}
